#define START_JUMPING "jump"
#define START_ACCELERATING_FORWARD "right"
#define START_ACCELERATING_BACKWARDS "left"
#define START_FLIPING_RIGHT "flip right"
#define START_FLIPING_LEFT "flip left"
#define START_TURNING "start turning"
#define START_DOING_TURBO "turbo"

#define STOP_JUMPING "stop jump"
#define STOP_ACCELERATING "stop accelerating"
#define STOP_FLIPING "stop flip"
#define STOP_TURNING "stop turning"
#define STOP_FLIPING_RIGHT "stop right"
#define STOP_FLIPING_LEFT "stop left"
#define STOP_DOING_TURBO "stop turbo"

#define DO_FLIP_SHOT "do flip shot"
#define DO_RED_SHOT "do red shot"
#define DO_PURPLE_SHOT "do pruple shot"
#define DO_GOLDEN_SHOT "do golden shot"

#define SKIP_REPLAY "skip replay"
#define QUIT "quit"